apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: devops-tools
spec:
  selector: 
    app: gitea
  type: NodePort  
  ports:
    - port: 80
      targetPort: 3000
      name: gitea-service
