apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-tools
spec:
  selector: 
    app: nexus-server
  type: NodePort  
  ports:
    - port: 80
      targetPort: 8081
      name: webui
    - port: 5000
      targetPort: 5000
      name: dockerrepo